alias createproject="django-admin startproject $1"
alias createsuperuser="python3 manage.py createsuperuser"
alias migrate="python3 manage.py migrate"
alias runserver="python3 manage.py runserver"
alias makemigrations="python3 manage.py makemigrations"
alias startapp="python3 manage.py startapp $1 "
