# Generated by Django 4.2.4 on 2023-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='responded_to',
            field=models.BooleanField(default=False),
        ),
    ]
