# Generated by Django 4.2.4 on 2023-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_view_counts_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_counts',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
