# Generated by Django 4.2.4 on 2023-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blog_slug_alter_blog_title_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='blog_image'),
        ),
    ]
